
import React from 'react';
import { 
  Home, 
  Target, 
  Settings, 
  Wallet, 
  TrendingUp, 
  TrendingDown, 
  Calendar, 
  ChevronLeft, 
  ChevronRight,
  // Added ChevronDown and ChevronUp to fix missing export errors in FixedExpenses.tsx
  ChevronDown,
  ChevronUp,
  Plus, 
  Trash2, 
  Edit2, 
  X, 
  CheckCircle2, 
  AlertCircle, 
  Fuel, 
  ScrollText, 
  Receipt, 
  Repeat, 
  Clock, 
  CreditCard, 
  Lock, 
  Users, 
  Activity, 
  BarChart3, 
  Smartphone, 
  Info, 
  Utensils, 
  Wrench, 
  ShoppingBag,
  PieChart
} from 'lucide-react';

export { 
  Home, 
  Target, 
  Settings, 
  Wallet, 
  TrendingUp, 
  TrendingDown, 
  Calendar, 
  ChevronLeft, 
  ChevronRight, 
  // Added ChevronDown and ChevronUp to fix missing export errors in FixedExpenses.tsx
  ChevronDown,
  ChevronUp,
  Plus, 
  Trash2, 
  Edit2, 
  X, 
  CheckCircle2, 
  AlertCircle, 
  Fuel, 
  ScrollText, 
  Receipt, 
  Repeat, 
  Clock, 
  CreditCard, 
  Lock, 
  Users, 
  Activity, 
  BarChart3, 
  Smartphone, 
  Info, 
  Utensils, 
  Wrench, 
  ShoppingBag,
  PieChart
};